
server:
  port: 8080


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jxpt
    username: root
    password: rbJ(E!5mEFBuT3G5fSAF
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB


